-- upgrade --
CREATE TABLE IF NOT EXISTS "authtoken" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "token" TEXT,
    "refresh_token" TEXT
);
CREATE TABLE IF NOT EXISTS "user" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "username" VARCHAR(255) NOT NULL UNIQUE,
    "firstname" VARCHAR(25) NOT NULL,
    "lastname" VARCHAR(25) NOT NULL,
    "email" VARCHAR(320) NOT NULL UNIQUE,
    "password" VARCHAR(4096) NOT NULL
);
CREATE TABLE IF NOT EXISTS "chat" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "owner_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "last_active" TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS "friend" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "of_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
    "user_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "message" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "content" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "author_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
    "receiver_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSON NOT NULL
);
